### ISSUE TITLE
multiple xml file in contexts foler may cause unpredictable results in raplaserver

### ISSUE THREAD

**Issue by xpertservice** [rapla/rapla#516]
Scenario: 

1 backup "rapla.xml" to "rapla - kopie.xml"
2. modify rapla.xml
2. Launch raplaserver.bat
Check log file:
 13:47:40.641 [main] INFO  DeploymentManager.addApp o.e.jetty.deploy.DeploymentMa
nager - Deployable added: D:\rapla-binary-1.8.4\rapla-binary-1.8.4\contexts\rapl
a - kopie.xml

The use of "rapla - kopie.xml" by raplaserver was not exepected.

**Comment by kohlhaas** [comment]
just tested. Works here.  Did you also modify the context path of rapla and rapla - kopie

**Comment by xpertservice** [comment]
Hi Chris,

Found the missing piece. I had only rapla - kopie.xml.
This means that jetty takes whatever it finds in the folder. :-(
