### ISSUE TITLE
Demo site is broken @ http://rapla-rapla.rhcloud.com/rapla

### ISSUE THREAD

**Issue by tesch1** [rapla/rapla#531]
HTTP Status 500 - Error during initialization see logs for details: org.rapla.server.internal.ServerServiceImpl could not be initialized due to null

**Comment by kohlhaas** [comment]
Thank you for this error report, i reset the data.

Rapla currently does not like it if the admin removes the parent category
usergroups. Will fix the issue in the next release.

Regards

Chrsitopher

Christopher Kohlhaas

Geschäftsführer

erdkante GmbH
Firmensitz: Piusstraße 2, 50823 Köln
Telefon: +49 221 16532794
Fax:  +49 221 97794218
Email: info@erdkante.de
Registergericht: Amtsgericht Köln, HRB 83659
Geschäftsführer: Martin Geuer, Christopher Kohlhaas

2016-09-12 13:28 GMT+02:00 Michael Tesch notifications@github.com:

**Comment by Clausinho** [comment]
It is broken again

`rapla-rapla.rhcloud.com’s server DNS address could not be found.`

**Comment by kohlhaas** [comment]
rapla demo site is up. But with current not stable trunk version

**Comment by Clausinho** [comment]
Thank you, it works @ http://rapla.org/rapla-demo/rapla/index
and username = admin + empty password
