### ISSUE TITLE
lost administrator rights in rapla

### ISSUE THREAD

**Issue by Carolinenhof** [rapla/rapla#534]
Hallo,

sorry, for writing here. But I have a really big problem: We are using one user with one password for rapla with admin-rights.

But now I have no more ressources to create. I can only plan new events, but no new ressources. 

(nochmal in deutsch: Seit heute morgen haben wir keine Admin-REchte mehr, aber nur diesen einen Zugang in Rapla. Ich kann keine Ressourcen oder Gruppen mehr anlegen, nur noch Veranstaltungen anlegen. Hat jemand eine Idee. Ich bin wirklich verzweifelt.)

Thank you very much.

**Comment by icare4-rapla** [comment]
Hi,

What version of  Rapla, which operating system, which database software or
storage method is being used?

Regards,

Bob



2017-02-08 11:57 GMT+01:00 Carolinenhof <notifications@github.com>:
