### ISSUE TITLE
Rapla Client

### ISSUE THREAD

**Issue by JuliCodes** [rapla/rapla#536]
Hello,
i'm currently working on a project for my university. And for this i have to get some information out of rapla.
I tried to compile the given RaplaConnectorTest.java and run it. 

Unfortunately i just get: `java.lang.NoSuchMethodException: org.rapla.client.swing.dagger.DaggerRaplaJavaClientComponent.getClientFacade()`

I hope somebody can help me to get it working :)

Greetings

**Comment by kohlhaas** [comment]
Hi Pbeckmann,

try the 1_8 branch. The current trunk includes experimental code generation, which is not that easy to setup in eclipse.

But you can also try generating code by executing maven compile.
