### ISSUE TITLE
Deleting a ressource : Dependencies exist for these objects

### ISSUE THREAD

**Issue by TCDTRapla** [rapla/rapla#539]
Hello, I want to delete a resource. The problem :

![unable to delete a ressource 170612](https://user-images.githubusercontent.com/28975080/27056767-cd4cea3a-4fc9-11e7-8cd1-041d461f5448.JPG)
How to fix this?
Thanks for your help

**Comment by kohlhaas** [comment]
The admin user has a filter that is referencing the resource. You have to delete or change that filter.

**Comment by TCDTRapla** [comment]
Thank you for your reply
I tried to find where to change or remove the filter. It seems to me that I do not know where to look. Would you let me know how?
![rapla issue admin filter 170613 1](https://user-images.githubusercontent.com/28975080/27072498-d752d4c0-5020-11e7-9753-d438c9fb84f2.JPG)
![rapla issue admin filter 170613 2](https://user-images.githubusercontent.com/28975080/27072499-d75393ce-5020-11e7-9824-de0f056d808e.JPG)
![rapla issue admin filter 170613 3](https://user-images.githubusercontent.com/28975080/27072500-d756d5c0-5020-11e7-9613-6f6cfddc857d.JPG)

**Comment by kohlhaas** [comment]
The last screenshot is the correct one. But maybe you have other exports in the drop-down (besides Defaut).

If there is no other calender with the filter try looking under options/notification.

**Comment by TCDTRapla** [comment]
Well, I tried many things: export csv / deleting a backup other than default / Options / notification => no result
![rapla issue admin filter 170613 filter](https://user-images.githubusercontent.com/28975080/27076137-954acf5e-502c-11e7-8ed4-16a1f58d803b.JPG)
![rapla issue admin filter 170613 options notification](https://user-images.githubusercontent.com/28975080/27076142-973c3ef6-502c-11e7-90d8-25ae5e7938de.JPG)

**Comment by kohlhaas** [comment]
you can also try to find the line in data.xml under the preference entry. There should be resource ref somewhere. Try deleting that line, but make a backup of data.xml before.

**Comment by TCDTRapla** [comment]
With your help and patience, I will get there!

I did not find data under preference in the program, but in the folder data> data.xml
Is this the next line that I have to delete?
<Dynatt: training>
             <Dynatt: training> # FFFF33 </ dynatt: training>
             <Dynatt: text> 0 1 DUMA GC1 </ dynatt: text>
          </ Dynatt: training>
          <Rapla: permission access = "allocate_conflicts" />
       </ Rapla: resource>
       "Last-changed =" "created-at =" 2017-06-07T15: 17: 48.0286Z "<prefix: resource id =" rfb21faa-b033-44d2-b76d-5c43adb00ffb " "2017-06-12T06: 15: 58.0985Z" last-changed-by = "ud0f00cd-aba2-4ab6-bdc3-9107f65b5494">
  
If I do, rapla will not start anymore

**Comment by kohlhaas** [comment]
search for the text rfb21faa-b033-44d2-b76d-5c43adb00ffb in data.xml (that is the id of the resource)

**Comment by TCDTRapla** [comment]
I found the ID in two places:
------------------
 <dynatt:formations>
    <dynatt:formations>#ffff33</dynatt:formations>
            <dynatt:texte>0 1 DUMA GC1</dynatt:texte>
         </dynatt:formations>
         <rapla:permission access="allocate_conflicts"/>
      </rapla:resource>
      <rapla:resource id="rfb21faa-b033-44d2-b76d-5c43adb00ffb" owner="ud0f00cd-aba2-4ab6-bdc3-9107f65b5494" created-at="2017-06-07T15:17:48.0286Z" last-changed="2017-06-12T06:15:58.0985Z" last-changed-by="ud0f00cd-aba2-4ab6-bdc3-9107f65b5494">
--------------- 
 </rapla:appointment>
         <rapla:allocate idref="rfb21faa-b033-44d2-b76d-5c43adb00ffb"/>
         <rapla:permission group="category[key='read-events-from-others']" access="read"/>
 ------------
If I delete one or both of them, Rapla don't run

What's next?

**Comment by kohlhaas** [comment]
Sorry it was the wrong id. it's the id from the resource before. I could not see because the text above 1 DUMA GC1 is missing. Search for the id attribute above the name DUMA GC1. That's the id of the resource you want.  Look for the second reference of that id.

**Comment by TCDTRapla** [comment]
here it is:
<rapla:resource id="r9564d65-85a9-4b47-8870-2e9c3bb0b56e" owner="ud0f00cd-aba2-4ab6-bdc3-9107f65b5494" created-at="2017-06-07T15:14:25.0183Z" last-changed="2017-06-13T16:58:29.0660Z" last-changed-by="ud0f00cd-aba2-4ab6-bdc3-9107f65b5494">
         <dynatt:formations>
            <dynatt:formations>#ffff33</dynatt:formations>
            <dynatt:texte>0 1 DUMA GC1</dynatt:texte>
         </dynatt:formations>
         <rapla:permission access="allocate_conflicts"/>
      </rapla:resource>
      <rapla:resource id="rfb21faa-b033-44d2-b76d-5c43adb00ffb" owner="ud0f00cd-aba2-4ab6-bdc3-9107f65b5494" created-at="2017-06-07T15:17:48.0286Z" last-changed="2017-06-12T06:15:58.0985Z" last-changed-by="ud0f00cd-aba2-4ab6-bdc3-9107f65b5494">

**Comment by kohlhaas** [comment]
same as above search for r9564d65-85a9-4b47-8870-2e9c3bb0b56e
and remove the referencing tag

**Comment by TCDTRapla** [comment]
Executed
thank you very much
