### ISSUE TITLE
Conflicts are not displayed

### ISSUE THREAD

**Issue by BENETNATH** [rapla/rapla#548]
Hello,
I'm trying to setup a new rapla instance no server, but i've also tried the 1.8.6 and 1.8.3 and I'm facing the same issue.
On a fresh install, i create an event and book the test resource. Everything is displayedd as it should.
I then create another event on the same time slot, the test ressource is displayed as red, normal. But if i create this event, i don't have any conflict notification. nowehere.
What could be the reason ?
Same with windows 7 or windows 10.
![test](https://user-images.githubusercontent.com/1931820/65683748-5f2f6500-e05e-11e9-84f4-2ac8d5b608eb.jpg)

**Comment by kohlhaas** [comment]
It's a feature. Conflicts in the past are no longer displayed. Try it for a date in the future

**Comment by BENETNATH** [comment]
Gosh, I feel a bit stupid then :) Thanks
